language: java
jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eRHFyAdqkUVlWxNrjy9UIN60tHEo+ZZl6l4lszFOFPqIuQKvX7NLI3+TBbvI0czVd9xZsNVLPYWwNxOqIbpMX/MBsXYdzDd2ne2E6Qvtq3OafzOe++vUIYi4YZlpfr3tSx3YNymhTne/KmDTJ/wfnmuemjgN9LWGph9GuaravQE="

notifications:
  email: false

sudo: false

#force travis to use a newer version of Java8.
addons:
  apt:
    packages:
      - oracle-java9-installer
  coverity_scan:
    project:
      name: "revapi/revapi"
      description: "Build submitted via Travis CI"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

cache:
  directories:
    - $HOME/.m2

#delete all our historic build artifacts so that the stale versions do
#not pollute the build. 
before_script:
  - rm -Rf $HOME/.m2/repository/org/revapi

script:
  - mvn clean verify --batch-mode --fail-at-end

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffc2f0f6f86121dd38e2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
- bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X xcode

